language: python
python:
  - '3.6'

#  command to install dependences
install:
  - 'pip install -r requirements.txt'

before-script:
  - codeclimate-test-report before-build

#  command to run tests
script:
  - nosetests --with-coverage --cover-tests
  - coverage report

after_success:
  - coveralls
